---
title: "Figure 5.5: Maps of areas with widely varying populations"
categories: 
  - figures
  - code
execute: 
  cache: true
  freeze: auto
---

Not too much to say here, except that it would be nice if somebody would develop a better approach to mapping US-wide data. Counties really are a terrible base unit.

```{r warning=FALSE, message=FALSE, results=FALSE}
library(sf)
library(tmap)
library(dplyr)

ca <- st_read("ca-pops.gpkg")

m1 <- tm_shape(ca) + 
  tm_fill(col = "population", 
          title = "Population", palette = "Reds") +
  tm_borders(col = "white", lwd = 0.5) + 
  tm_legend(position = c("left", "bottom")) +
  tm_layout(frame = FALSE, legend.width = 0.5)
  
m2 <- tm_shape(ca) + 
  tm_fill(col = "population", convert2density = TRUE, 
          title = "Pop density", palette = "Greens") +
  tm_borders(col = "white", lwd = 0.5) + 
  tm_legend(position = c("left", "bottom")) +
  tm_layout(frame = FALSE, legend.width = 0.5)

m3 <- tm_shape(ca) + 
  tm_fill(col = "population", convert2density = TRUE, 
          title = "Pop density", style = "log10_pretty", 
          palette = "Blues") +
  tm_borders(col = "white", lwd = 0.5) + 
  tm_legend(position = c("left", "bottom")) +
  tm_layout(frame = FALSE, legend.width = 0.5)
  
tmap_arrange(m1, m2, m3)
```

```{r}
#| code-fold: true
# License (MIT)
#
# Copyright (c) 2023 David O'Sullivan
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to  permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
```
