project:
  type: website
  output-dir: docs

website:
  title: "Web resources for Computing Geographically"
  page-navigation: true

format:
  html:
    theme: 
      light: superhero
      dark: darkly
    css: styles.css
    toc: true



