project:
  type: website
  output-dir: docs

website:
  title: "_Computing Geographically_ Bonus Material"
  favicon: favicon.ico
  navbar: 
    left:
      - text: Chapters
        menu:
          - text: "Building Bridges"
            file: "chapters/chap1/index.qmd"
          - text: "Location and Space"
            file: "chapters/chap2/index.qmd"
          - text: "Scale and Projection"
            file: "chapters/chap3/index.qmd"
          - text: "Place and Meaning in Space"
            file: "chapters/chap4/index.qmd"
          - text: "Lines and Areas"
            file: "chapters/chap5/index.qmd"
          - text: "Relations, Networks, Flows"
            file: "chapters/chap6/index.qmd"
          - text: "Time and Dynamics"
            file: "chapters/chap7/index.qmd"
          - text: "Process and Pattern"
            file: "chapters/chap8/index.qmd"
          - text: "Doing Giscience Doing Geography"
            file: "chapters/chap9/index.qmd"
      - text: Odds and ends
        file: "posts.qmd"
      - text: All the pages
        file: "index-listing.qmd"
  page-navigation: true
  body-footer: "&copy; 2023 David O'Sullivan"

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    # mainfont: "Libre Baskerville"
    code-fold: show
 
