project:
  type: website
  output-dir: docs

website:
  title: "Resources for _Computing Geographically_"
  navbar: 
    left:
      - text: Links
        menu:
          - text: "Building Bridges"
            file: "chap1.qmd"
          - text: "Location and Space"
            file: "chap2.qmd"
          - text: "Scale and Projection"
            file: "chap3.qmd"
          - text: "Place and Meaning in Space"
            file: "chap4.qmd"
          - text: "Lines and Areas"
            file: "chap5.qmd"
          - text: "Relations, Networks, Flows"
            file: "chap6.qmd"
          - text: "Time and Dynamics"
            file: "chap7.qmd"
          - text: "Process and Pattern"
            file: "chap8.qmd"
      
  page-navigation: true

format:
  html:
    theme: 
      light: superhero
      dark: darkly
    css: styles.css
    toc: true



