project:
  type: website
  output-dir: docs

website:
  title: "_Computing Geographically_ Bonus Material"
  favicon: favicon.ico
  navbar: 
    left:
      - text: Figures
        menu:
          - text: "1. Building Bridges"
            file: "chapters/chap1/index.qmd"
          - text: "2. Location and Space"
            file: "chapters/chap2/index.qmd"
          - text: "3. Scale and Projection"
            file: "chapters/chap3/index.qmd"
          - text: "4. Place and Meaning in Space"
            file: "chapters/chap4/index.qmd"
          - text: "5. Lines and Areas"
            file: "chapters/chap5/index.qmd"
          - text: "6. Relations, Networks, Flows"
            file: "chapters/chap6/index.qmd"
          - text: "7. Time and Dynamics"
            file: "chapters/chap7/index.qmd"
          - text: "8. Process and Pattern"
            file: "chapters/chap8/index.qmd"
          - text: "9. Doing Giscience Doing Geography"
            file: "chapters/chap9/index.qmd"
      - text: Links
        menu:
          - text: "1. Building Bridges"
            file: "links/links-1.qmd"
          - text: "2. Location and Space"
            file: "links/links-2.qmd"
          - text: "3. Scale and Projection"
            file: "links/links-3.qmd"
          - text: "4. Place and Meaning in Space"
            file: "links/links-4.qmd"
          - text: "5. Lines and Areas"
            file: "links/links-5.qmd"
          - text: "6. Relations, Networks, Flows"
            file: "links/links-6.qmd"
          - text: "7. Time and Dynamics"
            file: "links/links-7.qmd"
          - text: "8. Process and Pattern"
            file: "links/links-8.qmd"
      - text: Odds and ends
        file: "posts.qmd"
  page-navigation: true
  body-footer: "&copy; 2023 David O'Sullivan"

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    code-fold: show
 
