---
title: Chapter 5
subtitle: Lines and Areas
---

## Links 
### Figure 5.2
This Figure is a section of the map of the Cooch Behar enclave complex, available at [commons.wikimedia.org](https://commons.wikimedia.org/w/index.php?curid=15903195). Highly detailed maps of the enclave complex are available in Brendan Whyte's PhD thesis available [here](https://minerva-access.unimelb.edu.au/items/d213954c-283f-5196-b880-78f04ceae549).

### Figure 5.10
The data for this Figure are at the link noted in the Figure caption [github.com/lucguillemot/bayareageodemo](https://github.com/lucguillemot/bayareageodemo). An interactive map of the clusters can be viewed at [lucguillemot.github.io/bayareageodemo/](http://lucguillemot.github.io/bayareageodemo/). The map was designed by the very talented [Luc Guillemot](https://lucguillemot.com/).

### Footnote 17
The Manaaki Whenua Landcare Research's Land Environments of New Zealand website is at [landcareresearch.co.nz/tools-and-resources/mapping/lenz/](https://www.landcareresearch.co.nz/tools-and-resources/mapping/lenz/). Input data layers on which the LENZ classification was based are available at [lris.scinfo.org](https://lris.scinfo.org.nz/data/?q=LENZ).

