# Web resources for _Computing Geographically_
This repository contains copies of or links to web resources associated with my book [_Computing Geographically: Bridging Giscience and Geography_ (Guilford Press, New York)](https://www.guilford.com/books/Computing-Geographically/David-O'Sullivan/9781462553938).

Most of these resources are URLs in footnotes, which may change over time, so that the links become broken. I will try to keep them current here. They are listed below under headings numbered by chapter and footnote number (**footnote x.y**), or figure number (**fig x.y**).

## Chapter 1 Building Bridges
#### footnote 1.6 
You'll find my PhD thesis here: [Graph-based Cellular Automaton Models of Urban Spatial Processes](https://southosullivan.com/phd/). Chapter 2 is the slightly embarrassing take on space, mentioned in the note.

#### footnote 1.8 
Slides from the course I developed at Berkeley and taught from 2014 to 2018 [_Geog 80 Digital Worlds: An Introduction to Geospatial Technologies_](https://southosullivan.com/geog80/)</li>

## Chapter 2 Location and Space
#### footnote 2.1 
As marketing copy, this one is always already out of date. As of September 2023, the most direct reference to location on the Esri website is to be found here: [esri.com/en-us/arcgis/products/spatial-analytics-data-science/overview](https://www.esri.com/en-us/arcgis/products/spatial-analytics-data-science/overview). 

#### footnote 2.7 
_ScapeToad_ is still at [http://scapetoad.choros.place/](http://scapetoad.choros.place/) (yes `http`, not `https`).

#### footnote 2.8
The TopoJSON format specification is at [github.com/topojson/topojson-specification](https://github.com/topojson/topojson-specification).

#### footnote 2.9
The GeoJSON format specification is at [datatracker.ietf.org/doc/html/rfc7946](https://datatracker.ietf.org/doc/html/rfc7946)

#### footnote 2.10 
You can experiment with the GeoJSON format at [geojson.io](https://geojson.io/).

#### footnote 2.11 
David Theobald's bewildered comment about the rendering speed of shapefiles is in an article in _ArcUser_ entitled 'Understanding topology and shapefiles': [esri.com/news/arcuser/0401/topo.html](https://www.esri.com/news/arcuser/0401/topo.html).

#### footnote 2.14
The PostGIS project home page: [osgeo.org/projects/postgis/](https://www.osgeo.org/projects/postgis/)

## Chapter 3 Scale and Projection
#### footnote 3.3 
The Degree Confluence Project is at [confluence.org](https://confluence.org/).

#### footnote 3.5
Find out more about 'Null Island' (i.e., 0&deg;N 0&deg;E) at its [wikipedia page](https://en.wikipedia.org/wiki/Null_Island).

#### footnote 3.6
The original announcement of geohash is in this blogpost by Greg Niemeyer: [blog.labix.org/2008/02/26/geohashorg-is-public](https://blog.labix.org/2008/02/26/geohashorg-is-public). You can generate geohash codes at the website [http://geohash.org](http://geohash.org) (yes `http`, not `https`).

#### footnote 3.7 
Google's S2 index is explained at [s2geometry.io](https://s2geometry.io/).

#### footnote 3.8 
Uber's H3 index is described at [h3geo.org](https://h3geo.org/).

## Chapter 4 Place and Meaning in Space
#### fig 4.2
The Bostonography neighborhoods web map is unfortunately no longer working (worth a try, but likely won't work: [bostonography.com/hoods](https://bostonography.com/hoods/)). This [blogpost](https://bostonography.com/2012/crowdsourced-neighborhood-boundaries-part-one-consensus/) explains the idea, which someone really should revive in other places, as did Hayden Rickard in his Masters thesis, cited in the text and viewable at [this link](https://openaccess.wgtn.ac.nz/articles/thesis/Crowdsourcing_Neighbourhood_Delineations_in_Wellington_New_Zealand/17147960).

#### fig 4.3
The Nominatim geocoder is available at [nominatim.openstreetmap.org](https://nominatim.openstreetmap.org/ui/search.html).

#### fig 4.5
Chris McDowall's notes on the te reo Māori placenames map are at [github.com/fogonwater/we-are-here](https://github.com/fogonwater/we-are-here/tree/master/8_heart_memory#801-ingoa-w%C4%81hi-o-aotearoa--place-names-of-new-zealand). Te Hiku Media's ngā-kupu tools for detecting Māori words in text at at [github.com/TeHikuMedia/nga-kupu](https://github.com/TeHikuMedia/nga-kupu).

## Chapter 5 Lines and Areas
#### fig 5.2
This figure is a section of the map of the Cooch Behar enclave complex, available at [commons.wikimedia.org](https://commons.wikimedia.org/w/index.php?curid=15903195). Highly detailed maps of the enclave complex are available in Brendan Whyte's PhD thesis available [here](https://minerva-access.unimelb.edu.au/items/d213954c-283f-5196-b880-78f04ceae549).

#### fig 5.10
The data for this figure are at the link noted in the figure caption [github.com/lucguillemot/bayareageodemo](https://github.com/lucguillemot/bayareageodemo). An interactive map of the clusters can be viewed at [lucguillemot.github.io/bayareageodemo/](http://lucguillemot.github.io/bayareageodemo/). The map was designed by the very talented [Luc Guillemot](https://lucguillemot.com/).

#### footnote 5.17
The Manaaki Whenua Landcare Research's Land Environments of New Zealand website is at [landcareresearch.co.nz/tools-and-resources/mapping/lenz/](https://www.landcareresearch.co.nz/tools-and-resources/mapping/lenz/). Input data layers on which the LENZ classification was based are available at [lris.scinfo.org](https://lris.scinfo.org.nz/data/?q=LENZ).

## Chapter 6 Relations, Networks, Flows
#### footnote 6.5
The number of possible shortest paths, i.e., pairs of vertices, choosable from a graph of any given size is given by the numbers in [integer sequence A000522](https://oeis.org/A000522).

#### footnote 6.6
The World City Network basic data set is available at the [Globalisation and World Cities Research Network website](https://www.lboro.ac.uk/microsites/geography/gawc/datasets/da11.html). These data are used in figures 6.5, 6.6, and 6.13.

#### fig 6.5
See [above](#footnote-6.6).

#### fig 6.6
See [above](#footnote-6.6).

#### footnote 6.8
Stirling numbers of the 2nd kind are in [integer sequence A008277](https://oeis.org/A008277). You can obtain values of these numbers at [this web page](http://austinmohr.com/home/?page_id=431).

#### fig 6.7
The trade data used in this figure and in Figure 6.9 are [version 3 of the trade data](https://correlatesofwar.org/wp-content/uploads/COW_Trade_3.0.zip) currently available from the [Correlates of War website](https://correlatesofwar.org). 

#### fig 6.9
See [above](#fig6.7).

#### fig 6.13
See [above](#footnote-6.6).

## Chapter 7 Time and Dynamics
#### footnote 7.2
The 'timebliography' of representations of time in giscience is available at [http://spaceandtime.wsiabato.info/](http://spaceandtime.wsiabato.info/) (yes `http`, not `https`).

#### fig 7.6
The taxi trajectory dataset is available at [microsoft.com/en-us/research/publication/t-drive-trajectory-data-sample](https://www.microsoft.com/en-us/research/publication/t-drive-trajectory-data-sample/).

## Chapter 8 Process and Pattern
#### fig 8.4
The XKCD comic marking the passing of John Conway is at [xkcd.com](https://xkcd.com/2293).

#### footnote 8.14
Cosma Shalizi's notes on D'Arcy Thompson are at [http://bactra.org/notebooks/darcy-thompson.html](http://bactra.org/notebooks/darcy-thompson.html) (yes `http`, not `https`). Attention preservation notice: Cosma Shalizi's website is a rabbithole!
