---
title: "Figure 6.5"
---

```{r}
library(sf)
library(tmap)
library(geosphere)
library(igraph)
library(dplyr)
library(stringr)
library(smoothr)

setwd("~/Documents/code/computing-geographically/__scratch")
```

```{r}
cities <- read.csv("world-cities-network.csv")

network_data <- cities %>%
  select(-(name:LATITUDE))

geo_data <- cities %>%
  select(name:LATITUDE)
```

```{r}
network_data <- network_data %>%
  mutate(across(1:100, ~ ifelse(. < 4, 0, 1)))

keepers <- which(rowSums(network_data) > 0)
network_data <- network_data[keepers, ]
geo_data <- geo_data[keepers, ]

# incidences matrix
B <- network_data %>%
  as.matrix()
# adjacency matrix
A <- B %*% t(B)
A <- ifelse(A > 0, 1, 0)
diag(A) <- 0
```

```{r}
G <- graph_from_adjacency_matrix(A, mode = "undirected")

vertex_attr(G, "name") <- geo_data$name
vertex_attr(G, "lon") <- geo_data$LONGITUDE
vertex_attr(G, "lat") <- geo_data$LATITUDE

write.graph(G, "wcn-lon-lat.gml", "gml")
write.graph(G, "wcn-lon-lat.graphml", "graphml")
```

```{r}
plot.igraph(G, layout = layout.norm(geo_data[, 2:3] %>% as.matrix()), 
            rescale = FALSE,
            edge.curved = TRUE, 
            vertex.size = 2, 
            vertex.label.cex = 0.65,
            vertex.label.color = 'black', 
            edge.color = 'grey',
            edge.width = 0.25)
```

```{r}
data("World")

sf_use_s2(FALSE)

cut <- st_polygon(
  list(matrix(c(-90, -90,
                 90, -90,
                 90,  90,
                -90,  90,
                -90, -90), ncol = 2, byrow = TRUE))) %>%
  densify(100) %>%
  st_sfc() %>%
  st_sf(crs = 4326)

front <- World %>%
  st_intersection(cut)

back <- World %>%
  st_difference(cut)

sf_use_s2(TRUE)
```


```{r}
edges_sf <- as_edgelist(G) %>%
  as.data.frame
names(edges_sf) <- c("city1", "city2")

edges_sf <- edges_sf %>% 
  left_join(geo_data, by = join_by(city1 == name)) %>%
  rename(lon1 = LONGITUDE, lat1 = LATITUDE) %>%
  left_join(geo_data, by = join_by(city2 == name)) %>%
  rename(lon2 = LONGITUDE, lat2 = LATITUDE)

geodesics <- list()
for (i in 1:nrow(edges_sf)) {
  p1 <- edges_sf[i, c("lon1", "lat1")]
  p2 <- edges_sf[i, c("lon2", "lat2")]
  g <- gcIntermediate(p1, p2, breakAtDateLine = TRUE, addStartEnd = TRUE)
  geodesics[[i]] <- g
}

geodesics %>% st_multilinestring() %>%
  st_sfc() %>%
  st_cast("LINESTRING")

edges_sf %>% st_as_sf(geometry = )
```
