---
title: "Figure 3.7 Two simple world projections"
lightbox: true
categories: 
  - figures
  - code
  - R
execute: 
  cache: true
  freeze: auto
knitr:
  opts_chunk: 
    warning: false
    message: false
---

```{r message=FALSE}
library(sf)
library(ggplot2)
library(tmaptools)
library(dplyr)
```

Set up some theme stuff for the maps.

```{r}
#| code-fold: true

theme_set(theme_void())
theme_update(
  plot.margin = unit(c(0, 0, 0, 0), "pt"),
  plot.background = element_rect(fill = "#ddeeff"),
  panel.background = element_rect(fill = NA),
  panel.border = element_rect(fill = NA, linewidth = 0.5),
  panel.grid = element_line(colour = "black", linewidth = 0.05),
  panel.ontop = TRUE
)
```

Use the supplied `World` dataset (in lat-lon EPSG 4326) and make projections as required.

```{r}
data("World") 
world <- World %>%
  select(geometry)

# Equal area with standard parallel at 0
world_lcea <- world %>%
  st_transform("+proj=cea")
```

That's pretty much it. So here are the maps.

```{r fig.width=10, fig.height=5}
ggplot(world) +
  geom_sf(fill = "#aaeecc") +
  coord_sf(label_graticule = "", expand = FALSE) +
  scale_x_continuous(breaks = -12:12 * 15) +
  scale_y_continuous(breaks = -6:6 * 15)
```

```{r fig.width=10, fig.height=3.3}
ggplot(world_lcea) +
  geom_sf(fill = "#aaeecc") +
  coord_sf(label_graticule = "", expand = FALSE) +
  scale_x_continuous(breaks = -12:12 * 15) +
  scale_y_continuous(breaks = -6:6 * 15)
```

```{r}
#| code-fold: true
# License (MIT)
#
# Copyright (c) 2023 David O'Sullivan
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to  permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
```